# Generated by Django 4.2.1 on 2023-08-31 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import rrgg.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "area",
                "verbose_name_plural": "areas",
            },
        ),
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Consultant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "given_name",
                    models.CharField(max_length=64, verbose_name="given name"),
                ),
                (
                    "first_surname",
                    models.CharField(
                        max_length=64, verbose_name="first surname"
                    ),
                ),
                (
                    "second_surname",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="second surname",
                    ),
                ),
                (
                    "area",
                    models.ManyToManyField(
                        related_name="consultant",
                        to="rrgg.area",
                        verbose_name="area",
                    ),
                ),
            ],
            options={
                "verbose_name": "consultant",
                "verbose_name_plural": "consultants",
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("symbol", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=16)),
                ("name", models.CharField(max_length=128)),
                ("min_length", models.IntegerField(default=0)),
                ("max_length", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "document type",
            },
        ),
        migrations.CreateModel(
            name="InsurancePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        verbose_name="commission",
                    ),
                ),
            ],
            options={
                "verbose_name": "insurance plan",
                "verbose_name_plural": "insurance plans",
            },
        ),
        migrations.CreateModel(
            name="InsuranceVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="name"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="insurance_vehicle_images/",
                        verbose_name="logo",
                    ),
                ),
            ],
            options={
                "verbose_name": "vehicle insurance",
                "verbose_name_plural": "vehicle insurance",
            },
        ),
        migrations.CreateModel(
            name="InsuranceVehicleRatio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="tax (igv)",
                    ),
                ),
                (
                    "emission_right",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="emission right",
                    ),
                ),
                ("fee", models.PositiveIntegerField(null=True)),
                ("direct_debit", models.PositiveIntegerField(null=True)),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, unique=True),
                ),
                (
                    "insurance_vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ratios",
                        to="rrgg.insurancevehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IssuanceInsuranceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "issuance insurance status",
                "verbose_name_plural": "issuance insurance status",
            },
        ),
        migrations.CreateModel(
            name="IssuanceInsuranceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "issuance insurance type",
                "verbose_name_plural": "issuance insurance type",
            },
        ),
        migrations.CreateModel(
            name="IssuanceInsuranceVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy",
                    models.CharField(
                        max_length=64, verbose_name="policy number"
                    ),
                ),
                (
                    "collection_document",
                    models.CharField(
                        max_length=64, verbose_name="collection document"
                    ),
                ),
                (
                    "issuance_date",
                    models.DateTimeField(verbose_name="issuance_date"),
                ),
                (
                    "initial_validity",
                    models.DateTimeField(verbose_name="initial_validity"),
                ),
                (
                    "final_validity",
                    models.DateTimeField(verbose_name="final_validity"),
                ),
                (
                    "payment_document",
                    models.CharField(
                        max_length=64, verbose_name="payment document"
                    ),
                ),
                (
                    "plan_commission_percentage",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        verbose_name="plan commission percentage",
                    ),
                ),
                (
                    "comment",
                    models.TextField(null=True, verbose_name="comment"),
                ),
                (
                    "seller_commission_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="seller commission percentage",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "consultant_registrar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issuance_insurance_vehicles_registered",
                        to="rrgg.consultant",
                        verbose_name="registrar",
                    ),
                ),
                (
                    "consultant_seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issuance_insurance_vehicles_sold",
                        to="rrgg.consultant",
                        verbose_name="seller",
                    ),
                ),
                (
                    "insurance_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issuances",
                        to="rrgg.insuranceplan",
                    ),
                ),
                (
                    "issuance_type",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issuances",
                        to="rrgg.issuanceinsurancetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "issuance insurance vehicle",
                "verbose_name_plural": "issues insurance vehicle",
            },
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "given_name",
                    models.CharField(max_length=64, verbose_name="given name"),
                ),
                (
                    "first_surname",
                    models.CharField(
                        max_length=64, verbose_name="first surname"
                    ),
                ),
                (
                    "second_surname",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="second surname",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        verbose_name="document number",
                    ),
                ),
                ("birthdate", models.DateField(verbose_name="birthdate")),
                (
                    "phone_number",
                    models.CharField(
                        max_length=32, verbose_name="phone number"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=64, verbose_name="email"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "payment method",
                "verbose_name_plural": "payment methods",
            },
        ),
        migrations.CreateModel(
            name="QuotationInsuranceVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "insured_amount",
                    models.PositiveIntegerField(verbose_name="insured amount"),
                ),
                (
                    "consultant_registrar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotation_insurance_vehicles_registered",
                        to="rrgg.consultant",
                        verbose_name="registrar",
                    ),
                ),
                (
                    "consultant_seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotation_insurance_vehicles_sold",
                        to="rrgg.consultant",
                        verbose_name="seller",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotation_insurance_vehicles",
                        to="rrgg.currency",
                        verbose_name="currency",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotation_insurance_vehicles",
                        to="rrgg.customermembership",
                        verbose_name="customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "vehicle insurance quotation",
                "verbose_name_plural": "vehicle insurance quotations",
            },
        ),
        migrations.CreateModel(
            name="Risk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "risk",
                "verbose_name_plural": "risks",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "role",
                "verbose_name_plural": "roles",
            },
        ),
        migrations.CreateModel(
            name="UseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(max_length=64, verbose_name="brand"),
                ),
                (
                    "vehicle_model",
                    models.CharField(max_length=64, verbose_name="model"),
                ),
                (
                    "plate",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="plate"
                    ),
                ),
                (
                    "fabrication_year",
                    models.PositiveIntegerField(
                        verbose_name="fabrication year"
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        max_length=64, verbose_name="engine number"
                    ),
                ),
                (
                    "chassis",
                    models.CharField(
                        max_length=64, verbose_name="chassis number"
                    ),
                ),
                (
                    "seat_number",
                    models.PositiveIntegerField(verbose_name="seat number"),
                ),
                (
                    "has_gps",
                    models.BooleanField(
                        default=False, verbose_name="has gps?"
                    ),
                ),
                (
                    "has_endorsee",
                    models.BooleanField(
                        default=False, verbose_name="has endorsee?"
                    ),
                ),
                (
                    "endorsee_bank",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rrgg.bank",
                        verbose_name="endorsee bank",
                    ),
                ),
                (
                    "use_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="use_type",
                        to="rrgg.usetype",
                        verbose_name="usage",
                    ),
                ),
            ],
            options={
                "verbose_name": "vehicle",
                "verbose_name_plural": "vehicles",
            },
        ),
        migrations.CreateModel(
            name="VehicleOwnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ownership",
                        to="rrgg.customermembership",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ownership",
                        to="rrgg.owner",
                    ),
                ),
                (
                    "vehicle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ownership",
                        to="rrgg.vehicle",
                        verbose_name="vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RiskInsuranceVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insurance_vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rrgg.insurancevehicle",
                    ),
                ),
                (
                    "risk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rrgg.risk",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuotationInsuranceVehiclePremium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="net premium",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="rate"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        unique=True,
                        verbose_name="created at",
                    ),
                ),
                (
                    "insurance_vehicle_ratio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotation_insurance_vehicle_premiums",
                        to="rrgg.insurancevehicleratio",
                    ),
                ),
                (
                    "quotation_insurance_vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="premiums",
                        to="rrgg.quotationinsurancevehicle",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="quotationinsurancevehicle",
            name="risk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotation_insurances",
                to="rrgg.risk",
                verbose_name="risk",
            ),
        ),
        migrations.AddField(
            model_name="quotationinsurancevehicle",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotation_insurance_vehicles",
                to="rrgg.vehicle",
                verbose_name="vehicle",
            ),
        ),
        migrations.CreateModel(
            name="NaturalPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=32,
                        validators=[rrgg.validators.only_int],
                        verbose_name="phone number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=64, verbose_name="email"),
                ),
                (
                    "document_number",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        validators=[rrgg.validators.only_int],
                        verbose_name="document number",
                    ),
                ),
                (
                    "given_name",
                    models.CharField(max_length=64, verbose_name="given name"),
                ),
                (
                    "first_surname",
                    models.CharField(
                        max_length=64, verbose_name="first surname"
                    ),
                ),
                (
                    "second_surname",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="second surname",
                    ),
                ),
                ("birthdate", models.DateField(verbose_name="birthdate")),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rrgg.documenttype",
                        verbose_name="document type",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LegalPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=32,
                        validators=[rrgg.validators.only_int],
                        verbose_name="phone number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=64, verbose_name="email"),
                ),
                (
                    "document_number",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        validators=[rrgg.validators.only_int],
                        verbose_name="document number",
                    ),
                ),
                (
                    "registered_name",
                    models.CharField(
                        max_length=64, verbose_name="registered name"
                    ),
                ),
                (
                    "general_manager",
                    models.CharField(
                        max_length=64, verbose_name="general manager"
                    ),
                ),
                (
                    "anniversary_date",
                    models.DateField(verbose_name="anniversary date"),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rrgg.documenttype",
                        verbose_name="document type",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IssuanceInsuranceVehicleDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="documents/")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "issuance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="rrgg.issuanceinsurancevehicle",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="issuanceinsurancevehicle",
            name="payment_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issuances",
                to="rrgg.paymentmethod",
                verbose_name="payment method",
            ),
        ),
        migrations.AddField(
            model_name="issuanceinsurancevehicle",
            name="quotation_vehicle_premium",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issuance",
                to="rrgg.quotationinsurancevehiclepremium",
            ),
        ),
        migrations.AddField(
            model_name="issuanceinsurancevehicle",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issuances",
                to="rrgg.issuanceinsurancestatus",
            ),
        ),
        migrations.AddField(
            model_name="insuranceplan",
            name="risk_insurance_vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plans",
                to="rrgg.riskinsurancevehicle",
            ),
        ),
        migrations.AddField(
            model_name="customermembership",
            name="legal_person",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="membership",
                to="rrgg.legalperson",
            ),
        ),
        migrations.AddField(
            model_name="customermembership",
            name="natural_person",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="membership",
                to="rrgg.naturalperson",
            ),
        ),
        migrations.CreateModel(
            name="ConsultantRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new_sale",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="new sale",
                    ),
                ),
                (
                    "renewal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="renewal"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "consultant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_rate",
                        to="rrgg.consultant",
                        verbose_name="consultant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsultantMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership",
                        to="rrgg.consultant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultant_membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="consultant",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consultant",
                to="rrgg.role",
                verbose_name="role",
            ),
        ),
        migrations.CreateModel(
            name="CollectionInsuranceVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expiration_date", models.DateTimeField()),
                ("payment_date", models.DateTimeField(null=True)),
                (
                    "payment_receipt",
                    models.CharField(max_length=64, null=True),
                ),
                ("issue", models.CharField(max_length=64)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "issuance_vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collections",
                        to="rrgg.issuanceinsurancevehicle",
                    ),
                ),
            ],
        ),
    ]
