# Generated by Django 4.2.1 on 2023-07-15 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("give_name", models.CharField(max_length=64)),
                ("first_surname", models.CharField(max_length=64)),
                (
                    "second_surname",
                    models.CharField(blank=True, max_length=64),
                ),
                (
                    "document_number",
                    models.CharField(max_length=32, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("give_name", models.CharField(max_length=64)),
                ("first_surname", models.CharField(max_length=64)),
                (
                    "second_surname",
                    models.CharField(blank=True, max_length=64),
                ),
                (
                    "document_number",
                    models.CharField(max_length=32, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InsuranceVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="InsuranceVehiclePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_premium", models.PositiveIntegerField()),
                ("emission_right", models.PositiveIntegerField()),
                ("tax", models.PositiveIntegerField()),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, unique=True),
                ),
                (
                    "insurance_vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prices",
                        to="rrgg.insurancevehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=64)),
                ("vehicle_model", models.CharField(max_length=64)),
                (
                    "property_number",
                    models.CharField(max_length=64, unique=True),
                ),
                ("fabrication_year", models.PositiveIntegerField(default=0)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="rrgg.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuotationInsuranceVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("observations", models.TextField(blank=True, max_length=512)),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotation_insurance_vehicle",
                        to="rrgg.consultant",
                    ),
                ),
                (
                    "insurance_vehicle_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotation_insurance_vehicle",
                        to="rrgg.insurancevehicleprice",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotation_insurance_vehicle",
                        to="rrgg.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsultantMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership",
                        to="rrgg.consultant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultant_membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
