# Generated by Django 4.2.1 on 2023-07-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SeguroVehicular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prima_neta", models.PositiveIntegerField()),
                ("derecho_emision", models.PositiveIntegerField()),
                ("igv", models.PositiveIntegerField()),
            ],
        ),
    ]
