# Generated by Django 4.2.1 on 2023-08-31 21:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issuanceinsurancevehicle",
            name="payment_document",
        ),
    ]
