# Generated by Django 4.2.1 on 2023-07-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="segurovehicular",
            name="nombre",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
    ]
