# Generated by Django 4.2.1 on 2023-08-21 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=16)),
                ("name", models.CharField(max_length=128)),
                ("min_length", models.IntegerField(default=0)),
                ("max_length", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "document type",
            },
        ),
        migrations.CreateModel(
            name="NaturalPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=32, verbose_name="phone number"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=64, verbose_name="email"),
                ),
                (
                    "document_number",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        verbose_name="document number",
                    ),
                ),
                (
                    "given_name",
                    models.CharField(max_length=64, verbose_name="given name"),
                ),
                (
                    "first_surname",
                    models.CharField(
                        max_length=64, verbose_name="first surname"
                    ),
                ),
                (
                    "second_surname",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="second surname",
                    ),
                ),
                ("birthdate", models.DateField(verbose_name="birthdate")),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rrgg.documenttype",
                        verbose_name="document type",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LegalPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=32, verbose_name="phone number"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=64, verbose_name="email"),
                ),
                (
                    "document_number",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        verbose_name="document number",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        verbose_name="business name",
                    ),
                ),
                (
                    "registered_name",
                    models.CharField(
                        max_length=64, verbose_name="registered name"
                    ),
                ),
                (
                    "general_manager",
                    models.CharField(
                        max_length=64, verbose_name="general manager"
                    ),
                ),
                (
                    "anniversary_date",
                    models.DateField(verbose_name="anniversary date"),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rrgg.documenttype",
                        verbose_name="document type",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legal_person",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership",
                        to="rrgg.legalperson",
                    ),
                ),
                (
                    "natural_person",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership",
                        to="rrgg.naturalperson",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="quotationinsurancevehicle",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotation_insurance_vehicles",
                to="rrgg.customermembership",
                verbose_name="customer",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleownership",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ownership",
                to="rrgg.customermembership",
            ),
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
