# Generated by Django 4.2.1 on 2023-08-24 07:40

from django.db import migrations, models

import rrgg.validators


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0002_documenttype_naturalperson_legalperson_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legalperson",
            name="document_number",
            field=models.CharField(
                max_length=32,
                unique=True,
                validators=[rrgg.validators.only_int],
                verbose_name="document number",
            ),
        ),
        migrations.AlterField(
            model_name="legalperson",
            name="phone_number",
            field=models.CharField(
                max_length=32,
                validators=[rrgg.validators.only_int],
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="naturalperson",
            name="document_number",
            field=models.CharField(
                max_length=32,
                unique=True,
                validators=[rrgg.validators.only_int],
                verbose_name="document number",
            ),
        ),
        migrations.AlterField(
            model_name="naturalperson",
            name="phone_number",
            field=models.CharField(
                max_length=32,
                validators=[rrgg.validators.only_int],
                verbose_name="phone number",
            ),
        ),
    ]
