# Generated by Django 4.2.1 on 2023-07-14 21:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0002_segurovehicular_nombre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("give_name", models.CharField(default="", max_length=64)),
                ("first_surname", models.CharField(default="", max_length=64)),
                (
                    "second_surname",
                    models.CharField(default="", max_length=64),
                ),
                (
                    "dni",
                    models.CharField(
                        default="",
                        max_length=8,
                        validators=[
                            django.core.validators.MinLengthValidator(8),
                            django.core.validators.MaxLengthValidator(8),
                            django.core.validators.RegexValidator("^\\d+$"),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("give_name", models.CharField(default="", max_length=64)),
                ("first_surname", models.CharField(default="", max_length=64)),
                (
                    "second_surname",
                    models.CharField(default="", max_length=64),
                ),
                (
                    "dni",
                    models.CharField(
                        default="",
                        max_length=8,
                        validators=[
                            django.core.validators.MinLengthValidator(8),
                            django.core.validators.MaxLengthValidator(8),
                            django.core.validators.RegexValidator("^\\d+$"),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InsuranceVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="InsuranceVehiclePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=64)),
                ("business_premium", models.PositiveIntegerField()),
                ("emission_right", models.PositiveIntegerField()),
                ("igv", models.PositiveIntegerField()),
                (
                    "insurance_vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="insurance_vehicle_prices",
                        to="rrgg.insurancevehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InsuranceVehicleQuotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("hour", models.TimeField()),
                ("observations", models.CharField(default="", max_length=128)),
                (
                    "consultant",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="insurance_vehicle_quotation",
                        to="rrgg.consultant",
                    ),
                ),
                (
                    "insurance_vehicle_price",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="insurance_vehicle_quotation",
                        to="rrgg.insurancevehicleprice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(default="", max_length=64)),
                ("vehicle_model", models.CharField(default="", max_length=64)),
                (
                    "property_number",
                    models.CharField(default="", max_length=64),
                ),
                (
                    "fabrication_year",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinLengthValidator(4),
                            django.core.validators.MaxLengthValidator(4),
                        ],
                    ),
                ),
                ("use", models.CharField(default="", max_length=128)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="rrgg.customer",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="SeguroVehicular",
        ),
        migrations.AddField(
            model_name="insurancevehiclequotation",
            name="vehicle",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="insurance_vehicle_quotation",
                to="rrgg.vehicle",
            ),
        ),
    ]
