# Generated by Django 4.2.1 on 2023-09-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0002_remove_issuanceinsurancevehicle_payment_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuanceinsurancevehicle",
            name="final_validity",
            field=models.DateTimeField(verbose_name="final validity"),
        ),
        migrations.AlterField(
            model_name="issuanceinsurancevehicle",
            name="initial_validity",
            field=models.DateTimeField(verbose_name="initial validity"),
        ),
        migrations.AlterField(
            model_name="issuanceinsurancevehicle",
            name="issuance_date",
            field=models.DateTimeField(verbose_name="issuance date"),
        ),
    ]
