# Generated by Django 4.2.1 on 2023-07-14 21:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0003_consultant_customer_insurancevehicle_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="insurancevehicleprice",
            old_name="igv",
            new_name="tax",
        ),
        migrations.RemoveField(
            model_name="consultant",
            name="dni",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="dni",
        ),
        migrations.RemoveField(
            model_name="insurancevehicleprice",
            name="name",
        ),
        migrations.RemoveField(
            model_name="insurancevehiclequotation",
            name="date",
        ),
        migrations.RemoveField(
            model_name="insurancevehiclequotation",
            name="hour",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="use",
        ),
        migrations.AddField(
            model_name="consultant",
            name="document_number",
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="document_number",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="insurancevehicleprice",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="insurancevehiclequotation",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="consultant",
            name="first_surname",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="give_name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="second_surname",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="customer",
            name="first_surname",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="customer",
            name="give_name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="customer",
            name="second_surname",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="insurancevehicle",
            name="name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="insurancevehicleprice",
            name="insurance_vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prices",
                to="rrgg.insurancevehicle",
            ),
        ),
        migrations.AlterField(
            model_name="insurancevehiclequotation",
            name="observations",
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="brand",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="fabrication_year",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="property_number",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_model",
            field=models.CharField(max_length=64),
        ),
    ]
