# Generated by Django 4.2.1 on 2023-08-27 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0003_alter_legalperson_document_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Risk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "risk",
                "verbose_name_plural": "risks",
            },
        ),
        migrations.CreateModel(
            name="RiskInsuranceVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insurance_vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rrgg.insurancevehicle",
                    ),
                ),
                (
                    "risk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rrgg.risk",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InsurancePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        verbose_name="commission",
                    ),
                ),
                (
                    "risk_insurance_vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plans",
                        to="rrgg.riskinsurancevehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "insurance plan",
                "verbose_name_plural": "insurance plans",
            },
        ),
        migrations.AddField(
            model_name="quotationinsurancevehicle",
            name="risk",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotation_insurances",
                to="rrgg.risk",
                verbose_name="risk",
            ),
        ),
    ]
