# Generated by Django 4.2.1 on 2023-09-05 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "rrgg",
            "0003_alter_issuanceinsurancevehicle_final_validity_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectioninsurancevehicle",
            name="expiration_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="collectioninsurancevehicle",
            name="payment_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="issuanceinsurancevehicle",
            name="final_validity",
            field=models.DateField(verbose_name="final validity"),
        ),
        migrations.AlterField(
            model_name="issuanceinsurancevehicle",
            name="initial_validity",
            field=models.DateField(verbose_name="initial validity"),
        ),
        migrations.AlterField(
            model_name="issuanceinsurancevehicle",
            name="issuance_date",
            field=models.DateField(verbose_name="issuance date"),
        ),
        migrations.AlterField(
            model_name="quotationinsurancevehicle",
            name="consultant_seller",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotation_insurance_vehicles_sold",
                to="rrgg.consultant",
                verbose_name="seller",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="plate",
            field=models.CharField(
                max_length=64, null=True, unique=True, verbose_name="plate"
            ),
        ),
    ]
