# Generated by Django 4.2.1 on 2023-08-30 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0004_risk_riskinsurancevehicle_insuranceplan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("symbol", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="IssuanceInsuranceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "issuance insurance type",
                "verbose_name_plural": "issuance insurance type",
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="name"
                    ),
                ),
            ],
            options={
                "verbose_name": "payment method",
                "verbose_name_plural": "payment methods",
            },
        ),
        migrations.RemoveField(
            model_name="issuanceinsurancevehiclepolicy",
            name="issuanceinsurancevehicle_ptr",
        ),
        migrations.RemoveField(
            model_name="issuanceinsurancevehicle",
            name="consultant_new_sale_rate",
        ),
        migrations.RemoveField(
            model_name="issuanceinsurancevehicle",
            name="number_registry",
        ),
        migrations.RemoveField(
            model_name="legalperson",
            name="business_name",
        ),
        migrations.AddField(
            model_name="issuanceinsurancevehicle",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="amount",
            ),
        ),
        migrations.AddField(
            model_name="issuanceinsurancevehicle",
            name="collection_document",
            field=models.CharField(
                max_length=64, null=True, verbose_name="collection document"
            ),
        ),
        migrations.AddField(
            model_name="issuanceinsurancevehicle",
            name="insurance_plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issuances",
                to="rrgg.insuranceplan",
            ),
        ),
        migrations.AddField(
            model_name="issuanceinsurancevehicle",
            name="payment_document",
            field=models.CharField(
                max_length=64, null=True, verbose_name="payment document"
            ),
        ),
        migrations.AddField(
            model_name="issuanceinsurancevehicle",
            name="plan_commission_percentage",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="plan commission percentage",
            ),
        ),
        migrations.AddField(
            model_name="issuanceinsurancevehicle",
            name="policy",
            field=models.CharField(
                max_length=64, null=True, verbose_name="policy number"
            ),
        ),
        migrations.AddField(
            model_name="issuanceinsurancevehicle",
            name="seller_commission_percentage",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="seller commission percentage",
            ),
        ),
        migrations.AlterField(
            model_name="quotationinsurancevehicle",
            name="risk",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotation_insurances",
                to="rrgg.risk",
                verbose_name="risk",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="IssuanceInsuranceVehicleEndorsement",
        ),
        migrations.DeleteModel(
            name="IssuanceInsuranceVehiclePolicy",
        ),
        migrations.AddField(
            model_name="issuanceinsurancevehicle",
            name="issuance_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issuances",
                to="rrgg.issuanceinsurancetype",
            ),
        ),
        migrations.AddField(
            model_name="issuanceinsurancevehicle",
            name="payment_method",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issuances",
                to="rrgg.paymentmethod",
                verbose_name="payment method",
            ),
        ),
        migrations.AddField(
            model_name="quotationinsurancevehicle",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotation_insurance_vehicles",
                to="rrgg.currency",
                verbose_name="currency",
            ),
        ),
    ]
