# Generated by Django 4.2.1 on 2023-07-15 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0004_rename_igv_insurancevehicleprice_tax_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="second_surname",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="insurancevehiclequotation",
            name="consultant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="insurance_vehicle_quotation",
                to="rrgg.consultant",
            ),
        ),
    ]
