# Generated by Django 4.2.1 on 2023-09-08 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0005_alter_insurancevehicleratio_created_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="insurancevehicleratio",
            options={
                "verbose_name": "vehicle insurance ratio",
                "verbose_name_plural": "vehicle insurance ratios",
            },
        ),
        migrations.AlterField(
            model_name="quotationinsurancevehiclepremium",
            name="insurance_vehicle_ratio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotation_insurance_vehicle_premiums",
                to="rrgg.insurancevehicleratio",
                verbose_name="vehicle insurance ratio",
            ),
        ),
    ]
