# Generated by Django 4.2.1 on 2023-07-15 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrgg', '0005_alter_consultant_second_surname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InsuranceVehicleQuotation',
            new_name='QuotationInsuranceVehicle',
        ),
    ]
