# Generated by Django 4.2.1 on 2023-08-29 19:37

from decimal import Decimal

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0005_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuanceinsurancevehicle",
            name="amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                default_currency="PEN",
                max_digits=14,
            ),
        ),
    ]
