# Generated by Django 4.2.1 on 2023-07-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "rrgg",
            "0006_rename_insurancevehiclequotation_quotationinsurancevehicle",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="second_surname",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="customer",
            name="second_surname",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
