# Generated by Django 4.2.1 on 2023-09-14 04:17

import django.db.models.deletion
from django.db import migrations, models

import rrgg.validators


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0006_alter_insurancevehicleratio_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customermembership",
            name="seller",
            field=models.ForeignKey(
                default=9,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customers",
                to="rrgg.consultant",
            ),
        ),
        migrations.AddField(
            model_name="legalperson",
            name="address",
            field=models.CharField(
                max_length=128, null=True, verbose_name="address"
            ),
        ),
        migrations.AddField(
            model_name="legalperson",
            name="email2",
            field=models.EmailField(
                max_length=64, null=True, verbose_name="email 2"
            ),
        ),
        migrations.AddField(
            model_name="naturalperson",
            name="address",
            field=models.CharField(
                max_length=128, null=True, verbose_name="address"
            ),
        ),
        migrations.AddField(
            model_name="naturalperson",
            name="email2",
            field=models.EmailField(
                max_length=64, null=True, verbose_name="email 2"
            ),
        ),
        migrations.AlterField(
            model_name="legalperson",
            name="email",
            field=models.EmailField(
                max_length=64, null=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="legalperson",
            name="phone_number",
            field=models.CharField(
                max_length=32,
                null=True,
                validators=[rrgg.validators.only_int],
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="naturalperson",
            name="email",
            field=models.EmailField(
                max_length=64, null=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="naturalperson",
            name="phone_number",
            field=models.CharField(
                max_length=32,
                null=True,
                validators=[rrgg.validators.only_int],
                verbose_name="phone number",
            ),
        ),
    ]
