# Generated by Django 4.2.1 on 2023-08-29 20:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0006_alter_issuanceinsurancevehicle_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issuanceinsurancevehicle",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="issuanceinsurancevehicle",
            name="amount_currency",
        ),
        migrations.RemoveField(
            model_name="issuanceinsurancevehicle",
            name="currency",
        ),
        migrations.DeleteModel(
            name="Currency",
        ),
    ]
