# Generated by Django 4.2.1 on 2023-07-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0007_alter_consultant_second_surname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quotationinsurancevehicle",
            name="vehicle",
        ),
        migrations.AlterField(
            model_name="quotationinsurancevehicle",
            name="observations",
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
