# Generated by Django 4.2.1 on 2023-09-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "rrgg",
            "0007_customermembership_seller_legalperson_address_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="legalperson",
            name="anniversary_date",
            field=models.DateField(null=True, verbose_name="anniversary date"),
        ),
    ]
