# Generated by Django 4.2.1 on 2023-09-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0008_alter_legalperson_anniversary_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legalperson",
            name="general_manager",
            field=models.CharField(
                max_length=64, null=True, verbose_name="general manager"
            ),
        ),
        migrations.AlterField(
            model_name="legalperson",
            name="registered_name",
            field=models.CharField(
                max_length=128, verbose_name="registered name"
            ),
        ),
    ]
