# Generated by Django 4.2.1 on 2023-07-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrgg', '0009_quotationinsurancevehicle_vehicle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationinsurancevehicle',
            name='vehicle',
        ),
    ]
