# Generated by Django 4.2.1 on 2023-09-15 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0009_alter_legalperson_general_manager_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleownership",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ownership",
                to="rrgg.naturalperson",
            ),
        ),
        migrations.DeleteModel(
            name="Owner",
        ),
    ]
