# Generated by Django 4.2.1 on 2023-09-18 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0010_alter_vehicleownership_owner_delete_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customermembership",
            name="seller",
            field=models.ForeignKey(
                default=9,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customers",
                to="rrgg.consultant",
                verbose_name="seller",
            ),
        ),
    ]
