# Generated by Django 4.2.1 on 2023-07-15 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0010_remove_quotationinsurancevehicle_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotationinsurancevehicle",
            name="vehicle",
            field=models.OneToOneField(
                null=True,
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotation_insurance_vehicle",
                to="rrgg.vehicle",
            ),
            preserve_default=False,
        ),
    ]
