# Generated by Django 4.2.1 on 2023-09-20 22:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0011_alter_customermembership_seller"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="insurancevehicleratio",
            name="direct_debit",
        ),
        migrations.RemoveField(
            model_name="insurancevehicleratio",
            name="fee",
        ),
    ]
