# Generated by Django 4.2.1 on 2023-09-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0012_remove_insurancevehicleratio_direct_debit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotationinsurancevehiclepremium",
            name="emission_right_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.03,
                max_digits=10,
                verbose_name="emission right percentage",
            ),
        ),
        migrations.AddField(
            model_name="quotationinsurancevehiclepremium",
            name="tax_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.18,
                max_digits=10,
                verbose_name="tax percentage",
            ),
        ),
    ]
