# Generated by Django 4.2.1 on 2023-07-15 14:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0013_alter_quotationinsurancevehicle_vehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="document_number",
            field=models.CharField(max_length=32, null=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name="customer",
            name="document_number",
            field=models.CharField(max_length=32, null=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name="insurancevehicle",
            name="name",
            field=models.CharField(max_length=64, null=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name="insurancevehicleprice",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, null=True, default=uuid.uuid4
            ),
        ),
        migrations.AlterField(
            model_name="quotationinsurancevehicle",
            name="vehicle",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotation_insurance_vehicle",
                to="rrgg.vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="property_number",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
