# Generated by Django 4.2.1 on 2023-10-05 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0014_quotationinsurancevehicle_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssuanceInsuranceVehicleEndorsement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insured_amount",
                    models.PositiveIntegerField(verbose_name="insured amount"),
                ),
                (
                    "net_premium",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="net premium",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="rate"
                    ),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.18,
                        max_digits=10,
                        verbose_name="tax percentage",
                    ),
                ),
                (
                    "emission_right_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.03,
                        max_digits=10,
                        verbose_name="emission right percentage",
                    ),
                ),
                (
                    "collection_document",
                    models.CharField(
                        max_length=64, verbose_name="collection document"
                    ),
                ),
                (
                    "issuance_date",
                    models.DateField(verbose_name="issuance date"),
                ),
                (
                    "initial_validity",
                    models.DateField(verbose_name="initial validity"),
                ),
                (
                    "final_validity",
                    models.DateField(verbose_name="final validity"),
                ),
                (
                    "plan_commission_percentage",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        verbose_name="plan commission percentage",
                    ),
                ),
                (
                    "seller_commission_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="seller commission percentage",
                    ),
                ),
                ("detail", models.TextField(verbose_name="detail")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="endorsements",
                        to="rrgg.currency",
                        verbose_name="currency",
                    ),
                ),
                (
                    "issuance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endorsements",
                        to="rrgg.issuanceinsurancevehicle",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="endorsements",
                        to="rrgg.paymentmethod",
                        verbose_name="payment method",
                    ),
                ),
            ],
            options={
                "verbose_name": "issuance insurance endorsement",
                "verbose_name_plural": "issuance insurance endorsements",
                "abstract": False,
            },
        ),
    ]
