# Generated by Django 4.2.1 on 2023-10-14 22:35

from django.db import migrations, models


def get_issuance_premium_id(apps, schema_editor):
    Issuance = apps.get_model("rrgg", "IssuanceInsuranceVehicle")
    issuance_premium_id = []
    for issuance in Issuance.objects.all():
        if issuance.quotation_vehicle_premium:
            issuance_premium_id.append(
                (issuance.id, issuance.quotation_vehicle_premium.id)
            )
    schema_editor._issuance_premium_id = issuance_premium_id


def create_issuance_premiums_table(apps, schema_editor):
    Issuance = apps.get_model("rrgg", "IssuanceInsuranceVehicle")
    Premium = apps.get_model("rrgg", "QuotationInsuranceVehiclePremium")
    data = getattr(schema_editor, "_issuance_premium_id", [])
    for issuance_id, premium_id in data:
        issuance = Issuance.objects.get(pk=issuance_id)
        premium = Premium.objects.get(pk=premium_id)
        issuance.quotation_vehicle_premiums.add(premium)


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0015_issuanceinsurancevehicleendorsement"),
    ]

    operations = [
        migrations.RunPython(get_issuance_premium_id),
        migrations.RemoveField(
            model_name="issuanceinsurancevehicle",
            name="quotation_vehicle_premium",
        ),
        migrations.AddField(
            model_name="issuanceinsurancevehicle",
            name="quotation_vehicle_premiums",
            field=models.ManyToManyField(
                related_name="issuances",
                to="rrgg.quotationinsurancevehiclepremium",
            ),
        ),
        migrations.RunPython(create_issuance_premiums_table),
    ]
