# Generated by Django 4.2.1 on 2023-07-15 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rrgg", "0016_consultantmembership_consultant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultantmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consultant_membership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="quotationinsurancevehicle",
            name="consultant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotation_insurance_vehicle",
                to="rrgg.consultant",
            ),
        ),
        migrations.AlterField(
            model_name="quotationinsurancevehicle",
            name="insurance_vehicle_price",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotation_insurance_vehicle",
                to="rrgg.insurancevehicleprice",
            ),
        ),
        migrations.AlterField(
            model_name="quotationinsurancevehicle",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotation_insurance_vehicle",
                to="rrgg.vehicle",
            ),
        ),
    ]
