# Generated by Django 4.2.1 on 2023-10-25 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0017_endorsementvehicle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="endorsee_bank",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="rrgg.bank",
                verbose_name="endorsement bank",
            ),
        ),
        migrations.RenameField(
            model_name="vehicle",
            old_name="endorsee_bank",
            new_name="endorsement_bank",
        ),
    ]
