# Generated by Django 4.2.1 on 2023-10-27 03:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0017_alter_historicaldata_birth_date_and_more"),
        ("rrgg", "0018_remove_vehicle_endorsee_bank_and_more"),
    ]

    operations = []
