# Generated by Django 4.2.1 on 2023-07-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "rrgg",
            "0019_rename_property_number_vehicle_plate_vehicle_chassis_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="use_type",
            field=models.CharField(
                choices=[
                    ("particular", "Particular"),
                    ("public", "Public"),
                    ("commercial", "Commercial"),
                ],
                max_length=64,
            ),
        ),
    ]
