# Generated by Django 4.2.1 on 2023-10-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0020_alter_historicaldata_birth_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotationinsurancevehiclepremium",
            name="renewal_in_progress",
            field=models.BooleanField(
                default=False, verbose_name="renewal in progress"
            ),
        ),
    ]
