# Generated by Django 4.2.1 on 2023-07-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrgg', '0020_alter_vehicle_use_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='use_type',
        ),
    ]
