# Generated by Django 4.2.1 on 2023-11-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0021_quotationinsurancevehiclepremium_renewal_in_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultantrate",
            name="new_sale",
            field=models.DecimalField(
                decimal_places=4, max_digits=10, verbose_name="new sale"
            ),
        ),
        migrations.AlterField(
            model_name="consultantrate",
            name="renewal",
            field=models.DecimalField(
                decimal_places=4, max_digits=10, verbose_name="renewal"
            ),
        ),
        migrations.AlterField(
            model_name="endorsementvehicle",
            name="emission_right_percentage",
            field=models.DecimalField(
                decimal_places=4,
                default=0.03,
                max_digits=10,
                verbose_name="emission right percentage",
            ),
        ),
        migrations.AlterField(
            model_name="endorsementvehicle",
            name="plan_commission_percentage",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=10,
                verbose_name="plan commission percentage",
            ),
        ),
        migrations.AlterField(
            model_name="endorsementvehicle",
            name="rate",
            field=models.DecimalField(
                decimal_places=4, max_digits=10, verbose_name="rate"
            ),
        ),
        migrations.AlterField(
            model_name="endorsementvehicle",
            name="seller_commission_percentage",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=10,
                verbose_name="seller commission percentage",
            ),
        ),
        migrations.AlterField(
            model_name="endorsementvehicle",
            name="tax_percentage",
            field=models.DecimalField(
                decimal_places=4,
                default=0.18,
                max_digits=10,
                verbose_name="tax percentage",
            ),
        ),
        migrations.AlterField(
            model_name="insurancevehicleratio",
            name="emission_right",
            field=models.DecimalField(
                decimal_places=4, max_digits=10, verbose_name="emission right"
            ),
        ),
        migrations.AlterField(
            model_name="insurancevehicleratio",
            name="tax",
            field=models.DecimalField(
                decimal_places=4, max_digits=10, verbose_name="tax (igv)"
            ),
        ),
        migrations.AlterField(
            model_name="issuanceinsurancevehicle",
            name="plan_commission_percentage",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=10,
                verbose_name="plan commission percentage",
            ),
        ),
        migrations.AlterField(
            model_name="issuanceinsurancevehicle",
            name="seller_commission_percentage",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=10,
                verbose_name="seller commission percentage",
            ),
        ),
        migrations.AlterField(
            model_name="quotationinsurancevehiclepremium",
            name="emission_right_percentage",
            field=models.DecimalField(
                decimal_places=4,
                default=0.03,
                max_digits=10,
                verbose_name="emission right percentage",
            ),
        ),
        migrations.AlterField(
            model_name="quotationinsurancevehiclepremium",
            name="rate",
            field=models.DecimalField(
                decimal_places=4, max_digits=10, verbose_name="rate"
            ),
        ),
        migrations.AlterField(
            model_name="quotationinsurancevehiclepremium",
            name="tax_percentage",
            field=models.DecimalField(
                decimal_places=4,
                default=0.18,
                max_digits=10,
                verbose_name="tax percentage",
            ),
        ),
        migrations.AlterField(
            model_name="insuranceplan",
            name="commission",
            field=models.DecimalField(
                decimal_places=4, max_digits=10, verbose_name="commission"
            ),
        ),
        migrations.AlterField(
            model_name="endorsementvehicle",
            name="insured_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="insured amount"
            ),
        ),
    ]
