# Generated by Django 4.2.1 on 2023-07-19 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrgg', '0021_usetype_remove_vehicle_use_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='use_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='use_type', to='rrgg.usetype'),
            preserve_default=False,
        ),
    ]
