# Generated by Django 4.2.1 on 2023-07-21 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0023_quotationinsurancevehicle_amount_insured_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceVehiclePremium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_premium", models.PositiveIntegerField()),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InsuranceVehicleRatio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emission_right", models.PositiveIntegerField()),
                ("tax", models.PositiveIntegerField()),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, unique=True),
                ),
                (
                    "insurance_vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ratio",
                        to="rrgg.insurancevehicle",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="quotationinsurancevehicle",
            old_name="amount_insured",
            new_name="insured_amount",
        ),
        migrations.RemoveField(
            model_name="quotationinsurancevehicle",
            name="insurance_vehicle_price",
        ),
        migrations.RemoveField(
            model_name="quotationinsurancevehicle",
            name="observations",
        ),
        migrations.DeleteModel(
            name="InsuranceVehiclePrice",
        ),
        migrations.AddField(
            model_name="insurancevehiclepremium",
            name="insurance_vehicle_ratio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="insurance_vehicle_premium",
                to="rrgg.insurancevehicleratio",
            ),
        ),
        migrations.AddField(
            model_name="insurancevehiclepremium",
            name="quotation_insurance_vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="insurance_vehicle_premiums",
                to="rrgg.quotationinsurancevehicle",
            ),
        ),
    ]
