# Generated by Django 4.2.1 on 2023-07-22 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "rrgg",
            "0024_insurancevehiclepremium_insurancevehicleratio_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="insurancevehiclepremium",
            old_name="business_premium",
            new_name="amount",
        ),
        migrations.AlterField(
            model_name="insurancevehicleratio",
            name="insurance_vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ratios",
                to="rrgg.insurancevehicle",
            ),
        ),
    ]
