# Generated by Django 4.2.1 on 2023-07-22 17:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0026_alter_quotationinsurancevehicle_consultant_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InsuranceVehiclePremium",
            new_name="QuotationInsuranceVehiclePremium",
        ),
    ]
