# Generated by Django 4.2.1 on 2023-07-23 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "rrgg",
            (
                "0027_rename_insurancevehiclepremium"
                "_quotationinsurancevehiclepremium"
            ),
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurancevehicleratio",
            name="emission_right",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="insurancevehicleratio",
            name="tax",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="quotationinsurancevehicle",
            name="consultant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotation_insurance_vehicles",
                to="rrgg.consultant",
            ),
        ),
        migrations.AlterField(
            model_name="quotationinsurancevehicle",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotation_insurance_vehicles",
                to="rrgg.vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="quotationinsurancevehiclepremium",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="quotationinsurancevehiclepremium",
            name="insurance_vehicle_ratio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotation_insurance_vehicle_premiums",
                to="rrgg.insurancevehicleratio",
            ),
        ),
        migrations.AlterField(
            model_name="quotationinsurancevehiclepremium",
            name="quotation_insurance_vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="premiums",
                to="rrgg.quotationinsurancevehicle",
            ),
        ),
    ]
