# Generated by Django 4.2.1 on 2023-07-24 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0028_alter_insurancevehicleratio_emission_right_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Issuance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_number",
                    models.CharField(max_length=64, unique=True),
                ),
                (
                    "collection_document",
                    models.CharField(max_length=64, unique=True),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "insurance_vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issuance",
                        to="rrgg.insurancevehicle",
                    ),
                ),
                (
                    "quotation_vehicle_premium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issuance",
                        to="rrgg.quotationinsurancevehiclepremium",
                    ),
                ),
            ],
        ),
    ]
