# Generated by Django 4.2.1 on 2023-07-25 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0029_issuance"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssuanceInsuranceVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_number", models.CharField(max_length=64)),
                ("collection_document", models.CharField(max_length=64)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "quotation_vehicle_premium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issuance",
                        to="rrgg.quotationinsurancevehiclepremium",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Issuance",
        ),
    ]
