# Generated by Django 4.2.1 on 2023-07-26 00:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0030_issuanceinsurancevehicle_delete_issuance"),
        ("rrgg", "0030_rename_image_insurancevehicle_logo"),
    ]

    operations = []
