# Generated by Django 4.2.1 on 2023-07-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0031_merge_20230725_1943"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurancevehicleratio",
            name="direct_debit",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="insurancevehicleratio",
            name="fee",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="quotationinsurancevehicle",
            name="insured_amount",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
