# Generated by Django 4.2.1 on 2023-07-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0032_insurancevehicleratio_direct_debit_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issuanceinsurancevehicle",
            old_name="end_date",
            new_name="final_validity",
        ),
        migrations.RenameField(
            model_name="issuanceinsurancevehicle",
            old_name="start_date",
            new_name="initial_validity",
        ),
        migrations.RenameField(
            model_name="issuanceinsurancevehicle",
            old_name="policy_number",
            new_name="policy",
        ),
        migrations.AddField(
            model_name="issuanceinsurancevehicle",
            name="issuance_date",
            field=models.DateTimeField(null=True),
        ),
    ]
