# Generated by Django 4.2.1 on 2023-07-31 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "rrgg",
            (
                "0033_rename_end_date_issuanceinsurancevehicle"
                "_final_validity_and_more"
            ),
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionInsuranceVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expiration_date", models.DateTimeField()),
                ("payment_date", models.DateTimeField(null=True)),
                (
                    "payment_receipt",
                    models.CharField(max_length=64, null=True),
                ),
                ("issue", models.CharField(max_length=64)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "issuance_vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collections",
                        to="rrgg.issuanceinsurancevehicle",
                    ),
                ),
            ],
        ),
    ]
