# Generated by Django 4.2.1 on 2023-07-31 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0034_collectioninsurancevehicle"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consultant",
            options={
                "verbose_name": "consultant",
                "verbose_name_plural": "consultants",
            },
        ),
        migrations.AlterModelOptions(
            name="insurancevehicle",
            options={
                "verbose_name": "vehicle insurance",
                "verbose_name_plural": "vehicle insurance",
            },
        ),
        migrations.AlterModelOptions(
            name="quotationinsurancevehicle",
            options={
                "verbose_name": "vehicle insurance quotation",
                "verbose_name_plural": "vehicle insurance quotations",
            },
        ),
        migrations.AlterModelOptions(
            name="vehicle",
            options={
                "verbose_name": "vehicle",
                "verbose_name_plural": "vehicles",
            },
        ),
        migrations.AlterField(
            model_name="consultant",
            name="document_number",
            field=models.CharField(
                max_length=32, unique=True, verbose_name="document number"
            ),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="first_surname",
            field=models.CharField(
                max_length=64, verbose_name="first surname"
            ),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="given_name",
            field=models.CharField(max_length=64, verbose_name="given name"),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="second_surname",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="second surname"
            ),
        ),
        migrations.AlterField(
            model_name="insurancevehicle",
            name="name",
            field=models.CharField(
                max_length=64, unique=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="insurancevehicleratio",
            name="emission_right",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="emission right"
            ),
        ),
        migrations.AlterField(
            model_name="insurancevehicleratio",
            name="tax",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="tax (igv)"
            ),
        ),
        migrations.AlterField(
            model_name="quotationinsurancevehicle",
            name="consultant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotation_insurance_vehicles",
                to="rrgg.consultant",
                verbose_name="consultant",
            ),
        ),
        migrations.AlterField(
            model_name="quotationinsurancevehicle",
            name="insured_amount",
            field=models.PositiveIntegerField(
                null=True, verbose_name="insured amount"
            ),
        ),
        migrations.AlterField(
            model_name="quotationinsurancevehicle",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotation_insurance_vehicles",
                to="rrgg.vehicle",
                verbose_name="vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="quotationinsurancevehiclepremium",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="comercial premium",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="brand",
            field=models.CharField(max_length=64, verbose_name="brand"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="chassis",
            field=models.CharField(
                default="", max_length=64, verbose_name="chassis number"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vehicles",
                to="rrgg.customer",
                verbose_name="customer",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="engine",
            field=models.CharField(
                default="", max_length=64, verbose_name="engine number"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="fabrication_year",
            field=models.PositiveIntegerField(
                default=0, verbose_name="fabrication year"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="plate",
            field=models.CharField(
                max_length=64, unique=True, verbose_name="plate"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="use_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="use_type",
                to="rrgg.usetype",
                verbose_name="usage",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_model",
            field=models.CharField(max_length=64, verbose_name="model"),
        ),
    ]
