# Generated by Django 4.2.1 on 2023-07-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0035_alter_consultant_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="seat_number",
            field=models.PositiveIntegerField(
                default=None, verbose_name="seat number"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="chassis",
            field=models.CharField(
                max_length=64, verbose_name="chassis number"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="engine",
            field=models.CharField(
                max_length=64, verbose_name="engine number"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="fabrication_year",
            field=models.PositiveIntegerField(verbose_name="fabrication year"),
        ),
    ]
