# Generated by Django 4.2.1 on 2023-08-01 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0037_issuanceinsurancevehicle_endorsee_bank_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssuanceInsuranceVehicleDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="documents/")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "issuance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="rrgg.issuanceinsurancevehicle",
                    ),
                ),
            ],
        ),
    ]
