# Generated by Django 4.2.1 on 2023-08-05 15:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "rrgg",
            "0039_remove_issuanceinsurancevehicle_endorsee_bank_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IssuanceInsuranceVehicleDocuments",
            new_name="IssuanceInsuranceVehicleDocument",
        ),
    ]
