# Generated by Django 4.2.1 on 2023-08-07 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "rrgg",
            (
                "0040_rename_issuanceinsurancevehicledocuments"
                "_issuanceinsurancevehicledocument"
            ),
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "given_name",
                    models.CharField(max_length=64, verbose_name="given name"),
                ),
                (
                    "first_surname",
                    models.CharField(
                        max_length=64, verbose_name="first surname"
                    ),
                ),
                (
                    "second_surname",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="second surname",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        verbose_name="document number",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="customer",
        ),
        migrations.AddField(
            model_name="quotationinsurancevehicle",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotation_insurance_vehicles",
                to="rrgg.customer",
                verbose_name="customer",
            ),
        ),
        migrations.CreateModel(
            name="VehicleOwnerShip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ownership",
                        to="rrgg.customer",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ownership",
                        to="rrgg.owner",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="vehicle",
            name="owner_ship",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vehicle",
                to="rrgg.vehicleownership",
                verbose_name="owner ship",
            ),
        ),
    ]
