# Generated by Django 4.2.1 on 2023-08-10 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0041_owner_remove_vehicle_customer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssuanceInsuranceVehicleEndorsement",
            fields=[
                (
                    "issuanceinsurancevehicle_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="rrgg.issuanceinsurancevehicle",
                    ),
                ),
                (
                    "commission",
                    models.PositiveIntegerField(
                        null=True, verbose_name="commission"
                    ),
                ),
            ],
            bases=("rrgg.issuanceinsurancevehicle",),
        ),
        migrations.CreateModel(
            name="IssuanceInsuranceVehiclePolicy",
            fields=[
                (
                    "issuanceinsurancevehicle_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="rrgg.issuanceinsurancevehicle",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=64, null=True, verbose_name="description"
                    ),
                ),
            ],
            bases=("rrgg.issuanceinsurancevehicle",),
        ),
        migrations.RemoveField(
            model_name="issuanceinsurancevehicle",
            name="collection_document",
        ),
        migrations.RemoveField(
            model_name="issuanceinsurancevehicle",
            name="policy",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="owner_ship",
        ),
        migrations.AddField(
            model_name="issuanceinsurancevehicle",
            name="number_registry",
            field=models.CharField(
                max_length=64, null=True, verbose_name="number registry"
            ),
        ),
        migrations.AddField(
            model_name="vehicleownership",
            name="vehicle",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ownership",
                to="rrgg.vehicle",
                verbose_name="vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="issuanceinsurancevehicle",
            name="final_validity",
            field=models.DateTimeField(
                null=True, verbose_name="final validity"
            ),
        ),
        migrations.AlterField(
            model_name="issuanceinsurancevehicle",
            name="initial_validity",
            field=models.DateTimeField(verbose_name="initial validity"),
        ),
        migrations.AlterField(
            model_name="issuanceinsurancevehicle",
            name="issuance_date",
            field=models.DateTimeField(
                null=True, verbose_name="issuance date"
            ),
        ),
        migrations.AlterField(
            model_name="quotationinsurancevehiclepremium",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="net premium",
            ),
        ),
    ]
