# Generated by Django 4.2.1 on 2023-08-10 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0042_issuanceinsurancevehicleendorsement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssuanceInsuranceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "comment",
                    models.TextField(null=True, verbose_name="comment"),
                ),
            ],
            options={
                "verbose_name": "issuance insurance status",
                "verbose_name_plural": "issuance insurance status",
            },
        ),
        migrations.AlterModelOptions(
            name="issuanceinsurancevehicle",
            options={
                "verbose_name": "issuance insurance vehicle",
                "verbose_name_plural": "issues insurance vehicle",
            },
        ),
        migrations.AlterField(
            model_name="issuanceinsurancevehicle",
            name="final_validity",
            field=models.DateTimeField(
                null=True, verbose_name="final_validity"
            ),
        ),
        migrations.AlterField(
            model_name="issuanceinsurancevehicle",
            name="initial_validity",
            field=models.DateTimeField(
                null=True, verbose_name="initial_validity"
            ),
        ),
        migrations.AlterField(
            model_name="issuanceinsurancevehicle",
            name="issuance_date",
            field=models.DateTimeField(
                null=True, verbose_name="issuance_date"
            ),
        ),
        migrations.AddField(
            model_name="issuanceinsurancevehicle",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issuances",
                to="rrgg.issuanceinsurancestatus",
            ),
        ),
    ]
