# Generated by Django 4.2.1 on 2023-08-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0043_issuanceinsurancestatus_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issuanceinsurancestatus",
            name="comment",
        ),
        migrations.AddField(
            model_name="issuanceinsurancevehicle",
            name="comment",
            field=models.TextField(null=True, verbose_name="comment"),
        ),
    ]
