# Generated by Django 4.2.1 on 2023-08-12 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0045_role_remove_consultant_document_number_area_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quotationinsurancevehicle",
            name="consultant",
        ),
        migrations.AddField(
            model_name="quotationinsurancevehicle",
            name="consultant_registrar",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotation_insurance_vehicles_registered",
                to="rrgg.consultant",
                verbose_name="registrar",
            ),
        ),
        migrations.AddField(
            model_name="quotationinsurancevehicle",
            name="consultant_seller",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotation_insurance_vehicles_sold",
                to="rrgg.consultant",
                verbose_name="seller",
            ),
        ),
    ]
