# Generated by Django 4.2.1 on 2023-08-17 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0046_remove_quotationinsurancevehicle_consultant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuanceinsurancevehicle",
            name="consultant_new_sale_rate",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="consultant new sale rate",
            ),
        ),
        migrations.AddField(
            model_name="issuanceinsurancevehicle",
            name="consultant_registrar",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issuance_insurance_vehicles_registered",
                to="rrgg.consultant",
                verbose_name="registrar",
            ),
        ),
        migrations.AddField(
            model_name="issuanceinsurancevehicle",
            name="consultant_seller",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issuance_insurance_vehicles_sold",
                to="rrgg.consultant",
                verbose_name="seller",
            ),
        ),
        migrations.CreateModel(
            name="ConsultantRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new_sale",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="new sale",
                    ),
                ),
                (
                    "renewal",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="renewal",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "consultant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_rate",
                        to="rrgg.consultant",
                        verbose_name="consultant",
                    ),
                ),
            ],
        ),
    ]
