# Generated by Django 4.2.1 on 2023-08-17 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "rrgg",
            "0047_issuanceinsurancevehicle_consultant_new_sale_rate_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=64, null=True, unique=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="birthdate",
            field=models.DateField(null=True, verbose_name="birthdate"),
        ),
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                max_length=64, null=True, verbose_name="email"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(
                max_length=32, null=True, verbose_name="phone number"
            ),
        ),
        migrations.AddField(
            model_name="owner",
            name="birthdate",
            field=models.DateField(null=True, verbose_name="birthdate"),
        ),
        migrations.AddField(
            model_name="owner",
            name="email",
            field=models.EmailField(
                max_length=64, null=True, verbose_name="email"
            ),
        ),
        migrations.AddField(
            model_name="owner",
            name="phone_number",
            field=models.CharField(
                max_length=32, null=True, verbose_name="phone number"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="has_endorsee",
            field=models.BooleanField(
                default=False, verbose_name="has endorsee?"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="has_gps",
            field=models.BooleanField(default=False, verbose_name="has gps?"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="endorsee_bank",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="rrgg.bank",
                verbose_name="endorsee bank",
            ),
        ),
    ]
