# Generated by Django 4.2.1 on 2023-08-17 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rrgg", "0048_bank_customer_birthdate_customer_email_and_more"),
        ("rrgg", "0048_remove_area_consultant_consultant_area"),
    ]

    operations = []
